name: dht_dart
description: A DHT protocal implemented by Dart. This package implemented BEP-0005 for torrent client
version: 0.0.7
repository: https://github.com/eclipseglory/dht
issue_tracker : https://github.com/eclipseglory/dht/issues
publish_to: https://pub.dev/

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
   bencode_dart:
     git:
      url: https://github.com/PURUSHOTHAM-REDDY-N/bencode_dart.git
      ref: master 
   dartorrent_common:
     git:
      url: https://github.com/PURUSHOTHAM-REDDY-N/dartorrent_common.git
      ref: main 
dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  torrent_model:
    git:
      url: https://github.com/PURUSHOTHAM-REDDY-N/torrent_model.git
      ref: master 
