name: dht
description: A DHT protocal implemented by Dart.
version: 0.0.5
repository: https://github.com/eclipseglory/dht
issue_tracker : https://github.com/eclipseglory/dht/issues
publish_to: https://pub.dev/

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
   bencode_dart : ^1.0.2
   dartorrent_common: ^1.0.1
  #  dartorrent_common:
  #   path : '../../dartorrent_common'
dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  torrent_model : ^1.0.1
